services:
  - type: web
    name: c3-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn c3_app.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: SUPABASE_DB_NAME
        sync: false
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_PORT
        value: 5432
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DJANGO_SUPERUSER_USER_ID
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
